{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_func.py:19: Exception"}, "start": 1648451881114, "stop": 1648451881114, "uuid": "f10ce409-d592-4a7d-a24a-7af8deb74a66", "historyId": "6c2906976687a683adf75ce85ce6d6ca", "testCaseId": "ba9b4f4ce7069dd0db25b55f57c262a7", "fullName": "test_func#test_broken", "labels": [{"name": "suite", "value": "test_func"}, {"name": "host", "value": "NTCLT0302"}, {"name": "thread", "value": "432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_func"}]}